### ISSUE TITLE
trubrics flask sample app code not working

### ISSUE THREAD

**Issue by nirmalrayan** [trubrics/trubrics-sdk#91]
AttributeError
AttributeError: module 'trubrics' has no attribute 'init'

Traceback (most recent call last)
File "C:\Users\nrayan\Documents\Python Scripts\myvenv\Lib\site-packages\flask\app.py", line 2213, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nrayan\Documents\Python Scripts\myvenv\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nrayan\Documents\Python Scripts\myvenv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nrayan\Documents\Python Scripts\myvenv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nrayan\Documents\Python Scripts\myvenv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nrayan\Documents\Python Scripts\myvenv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nrayan\Documents\Python Scripts\myvenv\trubrics-sdk\examples\flask\flask_app.py", line 37, in submit_feedback
config = trubrics.init(email=os.environ["TRUBRICS_EMAIL"], password=os.environ["TRUBRICS_PASSWORD"])
         ^^^^^^^^^^^^^
AttributeError: module 'trubrics' has no attribute 'init'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by jeffkayne** [comment]
Thanks. We are currently making major changes to the sdk, and the Flask example will be updated then

**Comment by Kiiiiii123** [comment]
Hello, when can we use the next version sdk?
